/*
name: {
        info: {
            participe_passe: "",
            hilfsverb: "",
            deutsch: "",
        },
        forms: {
            present: {
                je: "",
                tu: "",
                il: "",
                nous: "",
                vous: "",
                ils: "",
            },
            imparfait: {
                je: "",
                tu: "",
                il: "",
                nous: "",
                vous: "",
                ils: "",
            },
            conditionnel: {
                je: "",
                tu: "",
                il: "",
                nous: "",
                vous: "",
                ils: "",
            },
            futur_simple: {
                je: "",
                tu: "",
                il: "",
                nous: "",
                vous: "",
                ils: "",
            },
            imperatif: {
                tu: "",
                nous: "",
                vous: "",
            },
            subjonctif: {
                je: "",
                tu: "",
                il: "",
                nous: "",
                vous: "",
                ils: "",
            },
        }
    }
*/

const verbs = {
    avoir: {
        info: {
            participe_passe: "eu",
            hilfsverb: "avoir",
            deutsch: "haben",
        },
        forms: {
            present: {
                je: "ai",
                tu: "as",
                il: "a",
                nous: "avons",
                vous: "avez",
                ils: "ont",
            },
            imparfait: {
                je: "avais",
                tu: "avais",
                il: "avait",
                nous: "avions",
                vous: "aviez",
                ils: "avaient",
            },
            conditionnel: {
                je: "aurais",
                tu: "aurais",
                il: "aurait",
                nous: "aurions",
                vous: "auriez",
                ils: "auraient",
            },
            futur_simple: {
                je: "aurai",
                tu: "auras",
                il: "aura",
                nous: "aurons",
                vous: "aurez",
                ils: "auront",
            },
            imperatif: {
                tu: "aie",
                nous: "ayons",
                vous: "ayez",
            },
            subjonctif: {
                je: "aie",
                tu: "aies",
                il: "aie",
                nous: "ayons",
                vous: "ayez",
                ils: "aient",
            },
        },
    },

    être: {
        info: {
            participe_passe: "été",
            hilfsverb: "avoir",
            deutsch: "sein",
        },
        forms: {
            present: {
                je: "suis",
                tu: "es",
                il: "est",
                nous: "sommes",
                vous: "êtes",
                ils: "sont",
            },
            imparfait: {
                je: "étais",
                tu: "étais",
                il: "était",
                nous: "étions",
                vous: "étiez",
                ils: "étaient",
            },
            conditionnel: {
                je: "serais",
                tu: "serais",
                il: "serait",
                nous: "serions",
                vous: "seriez",
                ils: "seraient",
            },
            futur_simple: {
                je: "serai",
                tu: "seras",
                il: "sera",
                nous: "serons",
                vous: "serez",
                ils: "seront",
            },
            imperatif: {
                tu: "sois",
                nous: "soyons",
                vous: "soyez",
            },
            subjonctif: {
                je: "sois",
                tu: "sois",
                il: "soit",
                nous: "soyons",
                vous: "soyez",
                ils: "soient",
            },
        }
    },

    aller: {
        info: {
            participe_passe: "allé",
            hilfsverb: "être",
            deutsch: "gehen",
        },
        forms: {
            present: {
                je: "vais",
                tu: "vas",
                il: "va",
                nous: "allons",
                vous: "allez",
                ils: "vont",
            },
            imparfait: {
                je: "allais",
                tu: "allais",
                il: "allait",
                nous: "allions",
                vous: "alliez",
                ils: "allaient",
            },
            conditionnel: {
                je: "irais",
                tu: "irais",
                il: "irait",
                nous: "irions",
                vous: "iriez",
                ils: "iraient",
            },
            futur_simple: {
                je: "irai",
                tu: "iras",
                il: "ira",
                nous: "irons",
                vous: "irez",
                ils: "iront",
            },
            imperatif: {
                tu: "va",
                nous: "allons",
                vous: "allez",
            },
            subjonctif: {
                je: "aille",
                tu: "ailles",
                il: "aille",
                nous: "allions",
                vous: "alliez",
                ils: "aillent",
            },
        }
    },
    venir: {
        info: {
            participe_passe: "venu",
            hilfsverb: "être",
            deutsch: "kommen",
        },
        forms: {
            present: {
                je: "viens",
                tu: "viens",
                il: "vient",
                nous: "venons",
                vous: "venez",
                ils: "viennent",
            },
            imparfait: {
                je: "venais",
                tu: "venais",
                il: "venait",
                nous: "venions",
                vous: "veniez",
                ils: "venaient",
            },
            conditionnel: {
                je: "viendrais",
                tu: "viendrais",
                il: "viendrait",
                nous: "viendrions",
                vous: "viendriez",
                ils: "viendraient",
            },
            futur_simple: {
                je: "viendrai",
                tu: "viendras",
                il: "viendra",
                nous: "viendrons",
                vous: "viendrez",
                ils: "viendront",
            },
            imperatif: {
                tu: "viens",
                nous: "venons",
                vous: "venez",
            },
            subjonctif: {
                je: "vienne",
                tu: "viennes",
                il: "vienne",
                nous: "venions",
                vous: "veniez",
                ils: "viennent",
            },
        }
    },
    chercher: {
        info: {
            participe_passe: "cherché",
            hilfsverb: "avoir",
            deutsch: "suchen",
        },
        forms: {
            present: {
                je: "cherche",
                tu: "cherches",
                il: "cherche",
                nous: "cherchons",
                vous: "cherchez",
                ils: "cherchent",
            },
            imparfait: {
                je: "cherchais",
                tu: "cherchais",
                il: "cherchait",
                nous: "cherchions",
                vous: "cherchiez",
                ils: "cherchaient",
            },
            conditionnel: {
                je: "chercherais",
                tu: "chercherais",
                il: "chercherait",
                nous: "chercherions",
                vous: "chercheriez",
                ils: "chercheraient",
            },
            futur_simple: {
                je: "chercherai",
                tu: "chercheras",
                il: "cherchera",
                nous: "chercherons",
                vous: "chercherez",
                ils: "chercheront",
            },
            imperatif: {
                tu: "cherche",
                nous: "cherchons",
                vous: "cherchez",
            },
            subjonctif: {
                je: "cherche",
                tu: "cherches",
                il: "cherche",
                nous: "cherchions",
                vous: "cherchiez",
                ils: "cherchent",
            },
        }
    },
    se_tromper: {
        info: {
            participe_passe: "trompé",
            hilfsverb: "être",
            deutsch: "sich irren",
        },
        forms: {
            present: {
                je: "me trompe",
                tu: "te trompes",
                il: "se trompe",
                nous: "nous trompons",
                vous: "vous trompez",
                ils: "se trompent",
            },
            imparfait: {
                je: "me trompais",
                tu: "te trompais",
                il: "se trompait",
                nous: "nous trompions",
                vous: "vous trompiez",
                ils: "se trompaient",
            },
            conditionnel: {
                je: "me tromperais",
                tu: "te tromperais",
                il: "se tromperait",
                nous: "nous tromperions",
                vous: "vous tromperiez",
                ils: "se tromperaient",
            },
            futur_simple: {
                je: "me tromperai",
                tu: "te tromperas",
                il: "se trompera",
                nous: "nous tromperons",
                vous: "vous tromperez",
                ils: "se tromperont",
            },
            imperatif: {
                tu: "trompe-toi",
                nous: "trompons-nous",
                vous: "trompez-vous",
            },
            subjonctif: {
                je: "me trompe",
                tu: "te trompes",
                il: "se trompe",
                nous: "nous trompions",
                vous: "vous trompiez",
                ils: "se trompent",
            },
        }
    },
    parler: {
        info: {
            participe_passe: "parlé",
            hilfsverb: "avoir",
            deutsch: "sprechen",
        },
        forms: {
            present: {
                je: "parle",
                tu: "parles",
                il: "parle",
                nous: "parlons",
                vous: "parlez",
                ils: "parlent",
            },
            imparfait: {
                je: "parlais",
                tu: "parlais",
                il: "parlait",
                nous: "parlions",
                vous: "parliez",
                ils: "parlaient",
            },
            conditionnel: {
                je: "parlerais",
                tu: "parlerais",
                il: "parlerait",
                nous: "parlerions",
                vous: "parleriez",
                ils: "parleraient",
            },
            futur_simple: {
                je: "parlerai",
                tu: "parleras",
                il: "parlera",
                nous: "parlerons",
                vous: "parlerez",
                ils: "parleront",
            },
            imperatif: {
                tu: "parle",
                nous: "parlons",
                vous: "parlez",
            },
            subjonctif: {
                je: "parle",
                tu: "parles",
                il: "parle",
                nous: "parlions",
                vous: "parliez",
                ils: "parlent",
            },
        }
    },
    manger: {
        info: {
            participe_passe: "mangé",
            hilfsverb: "avoir",
            deutsch: "essen",
        },
        forms: {
            present: {
                je: "mange",
                tu: "manges",
                il: "mange",
                nous: "mangeons",
                vous: "mangez",
                ils: "mangent",
            },
            imparfait: {
                je: "mangeais",
                tu: "mangeais",
                il: "mangeait",
                nous: "mangions",
                vous: "mangiez",
                ils: "mangeaient",
            },
            conditionnel: {
                je: "mangerais",
                tu: "mangerais",
                il: "mangerait",
                nous: "mangerions",
                vous: "mangeriez",
                ils: "mangeraient",
            },
            futur_simple: {
                je: "mangerai",
                tu: "mangeras",
                il: "mangera",
                nous: "mangerons",
                vous: "mangerez",
                ils: "mangeront",
            },
            imperatif: {
                tu: "mange",
                nous: "mangeons",
                vous: "mangez",
            },
            subjonctif: {
                je: "mange",
                tu: "manges",
                il: "mange",
                nous: "mangions",
                vous: "mangiez",
                ils: "mangent",
            },
        }
    },
    commencer: {
        info: {
            participe_passe: "commencé",
            hilfsverb: "avoir",
            deutsch: "beginnen",
        },
        forms: {
            present: {
                je: "commence",
                tu: "commences",
                il: "commence",
                nous: "commençons",
                vous: "commencez",
                ils: "commencent",
            },
            imparfait: {
                je: "commençais",
                tu: "commençais",
                il: "commençait",
                nous: "commencions",
                vous: "commenciez",
                ils: "commençaient",
            },
            conditionnel: {
                je: "commencerais",
                tu: "commencerais",
                il: "commencerait",
                nous: "commencerions",
                vous: "commenceriez",
                ils: "commenceraient",
            },
            futur_simple: {
                je: "commencerai",
                tu: "commenceras",
                il: "commencera",
                nous: "commencerons",
                vous: "commencerez",
                ils: "commenceront",
            },
            imperatif: {
                tu: "commence",
                nous: "commençons",
                vous: "commencez",
            },
            subjonctif: {
                je: "commence",
                tu: "commences",
                il: "commence",
                nous: "commencions",
                vous: "commenciez",
                ils: "commencent",
            },
        }
    },
    acheter: {
        info: {
            participe_passe: "acheté",
            hilfsverb: "avoir",
            deutsch: "kaufen",
        },
        forms: {
            present: {
                je: "achète",
                tu: "achètes",
                il: "achète",
                nous: "achetons",
                vous: "achetez",
                ils: "achètent",
            },
            imparfait: {
                je: "achetais",
                tu: "achetais",
                il: "achetait",
                nous: "achetions",
                vous: "achetiez",
                ils: "achetaient",
            },
            conditionnel: {
                je: "achèterais",
                tu: "achèterais",
                il: "achèterait",
                nous: "achèterionr",
                vous: "achèteriez",
                ils: "achèteraient",
            },
            futur_simple: {
                je: "achèterai",
                tu: "achèteras",
                il: "achètera",
                nous: "achèterons",
                vous: "achèterez",
                ils: "achèteront",
            },
            imperatif: {
                tu: "achète",
                nous: "achetons",
                vous: "achetez",
            },
            subjonctif: {
                je: "achète",
                tu: "achètes",
                il: "achète",
                nous: "achetions",
                vous: "achetiez",
                ils: "achètent",
            },
        }
    },
    préférer: {
        info: {
            participe_passe: "préféré",
            hilfsverb: "avoir",
            deutsch: "bevorzugen",
        },
        forms: {
            present: {
                je: "préfère",
                tu: "préfères",
                il: "préfère",
                nous: "préférons",
                vous: "préférez",
                ils: "préfèrent",
            },
            imparfait: {
                je: "préférais",
                tu: "préférais",
                il: "préférait",
                nous: "préférions",
                vous: "préfériez",
                ils: "préféraient",
            },
            conditionnel: {
                je: "préférerais",
                tu: "préférerais",
                il: "préférerait",
                nous: "préférerions",
                vous: "préféreriez",
                ils: "préféreraient",
            },
            futur_simple: {
                je: "préférerai",
                tu: "préféreras",
                il: "préférera",
                nous: "préférerons",
                vous: "préférerez",
                ils: "préféreront",
            },
            imperatif: {
                tu: "préfère",
                nous: "préférons",
                vous: "préférez",
            },
            subjonctif: {
                je: "préfère",
                tu: "préfères",
                il: "préfère",
                nous: "préfèrions",
                vous: "préfèriez",
                ils: "préfèrent",
            },
        }
    },
    appeler: {
        info: {
            participe_passe: "appelé",
            hilfsverb: "avoir",
            deutsch: "anrufen",
        },
        forms: {
            present: {
                je: "appelle",
                tu: "appelles",
                il: "appelle",
                nous: "appelons",
                vous: "appelez",
                ils: "appellent",
            },
            imparfait: {
                je: "appelais",
                tu: "appelais",
                il: "appelait",
                nous: "appelions",
                vous: "appeliez",
                ils: "appelaient",
            },
            conditionnel: {
                je: "appellerais",
                tu: "appellerais",
                il: "appellerait",
                nous: "appellerions",
                vous: "appelleriez",
                ils: "appelleraient",
            },
            futur_simple: {
                je: "appellerai",
                tu: "appelleras",
                il: "appellera",
                nous: "appellerons",
                vous: "appellerez",
                ils: "appelleront",
            },
            imperatif: {
                tu: "appelle",
                nous: "appelons",
                vous: "appelez",
            },
            subjonctif: {
                je: "appelle",
                tu: "appelles",
                il: "appelle",
                nous: "appelions",
                vous: "appeliez",
                ils: "appellent",
            },
        }
    },
    répéter: {
        info: {
            participe_passe: "répété",
            hilfsverb: "avoir",
            deutsch: "wiederholen",
        },
        forms: {
            present: {
                je: "répète",
                tu: "répètes",
                il: "répète",
                nous: "répétons",
                vous: "répétez",
                ils: "répétent",
            },
            imparfait: {
                je: "répétais",
                tu: "répétais",
                il: "répétait",
                nous: "répétions",
                vous: "répétiez",
                ils: "répétaient",
            },
            conditionnel: {
                je: "répéterais",
                tu: "répéterais",
                il: "répéterait",
                nous: "répéterions",
                vous: "répéteriez",
                ils: "répéteraient",
            },
            futur_simple: {
                je: "répéterai",
                tu: "répéteras",
                il: "répétera",
                nous: "répéterons",
                vous: "répéterez",
                ils: "répéteront",
            },
            imperatif: {
                tu: "répète",
                nous: "répétons",
                vous: "répétez",
            },
            subjonctif: {
                je: "répète",
                tu: "répètes",
                il: "répète",
                nous: "répétions",
                vous: "répétiez",
                ils: "répètent",
            },
        }
    },
    nettoyer: {
        info: {
            participe_passe: "nettoyé",
            hilfsverb: "avoir",
            deutsch: "reinigen",
        },
        forms: {
            present: {
                je: "nettoie",
                tu: "nettoies",
                il: "nettoie",
                nous: "nettoyons",
                vous: "nettoyez",
                ils: "nettoient",
            },
            imparfait: {
                je: "nettoyais",
                tu: "nettoyais",
                il: "nettoyait",
                nous: "nettoyions",
                vous: "nettoyiez",
                ils: "nettoyaient",
            },
            conditionnel: {
                je: "nettoierais",
                tu: "nettoierais",
                il: "nettoierait",
                nous: "nettoierions",
                vous: "nettoieriez",
                ils: "nettoieraient",
            },
            futur_simple: {
                je: "nettoierai",
                tu: "nettoieras",
                il: "nettoiera",
                nous: "nettoieron",
                vous: "nettoierez",
                ils: "nettoieront",
            },
            imperatif: {
                tu: "nettoie",
                nous: "nettoyons",
                vous: "nettoyez",
            },
            subjonctif: {
                je: "nettoie",
                tu: "nettoies",
                il: "nettoie",
                nous: "nettoyions",
                vous: "nettoyiez",
                ils: "nettoient",
            },
        }
    },
    jeter: {
        info: {
            participe_passe: "jeté",
            hilfsverb: "avoir",
            deutsch: "werfen",
        },
        forms: {
            present: {
                je: "jette",
                tu: "jettes",
                il: "jette",
                nous: "jetons",
                vous: "jetez",
                ils: "jettent",
            },
            imparfait: {
                je: "jetais",
                tu: "jetais",
                il: "jetait",
                nous: "jetions",
                vous: "jetiez",
                ils: "jetaient",
            },
            conditionnel: {
                je: "jetterais",
                tu: "jetterais",
                il: "jetterait",
                nous: "jetterions",
                vous: "jetteriez",
                ils: "jetteraient",
            },
            futur_simple: {
                je: "jetterai",
                tu: "jetteras",
                il: "jettera",
                nous: "jetterons",
                vous: "jetterez",
                ils: "jetteront",
            },
            imperatif: {
                tu: "jette",
                nous: "jetons",
                vous: "jetez",
            },
            subjonctif: {
                je: "jette",
                tu: "jettes",
                il: "jette",
                nous: "jetions",
                vous: "jetiez",
                ils: "jettent",
            },
        }
    },
    rappeler: {
        info: {
            participe_passe: "rappelé",
            hilfsverb: "avoir",
            deutsch: "erinnern",
        },
        forms: {
            present: {
                je: "rappelle",
                tu: "rappelles",
                il: "rappelle",
                nous: "rappelons",
                vous: "rappelez",
                ils: "rappellent",
            },
            imparfait: {
                je: "rappelais",
                tu: "rappelais",
                il: "rappelait",
                nous: "rappelions",
                vous: "rappeliez",
                ils: "rappelaient",
            },
            conditionnel: {
                je: "rappellerais",
                tu: "rappellerais",
                il: "rappellerait",
                nous: "rappellerions",
                vous: "rappelleriez",
                ils: "rappelleraient",
            },
            futur_simple: {
                je: "rappellerai",
                tu: "rappelleras",
                il: "rappellera",
                nous: "rappellerons",
                vous: "rappellerez",
                ils: "rappelleront",
            },
            imperatif: {
                tu: "rappelle",
                nous: "rappelons",
                vous: "rappelez",
            },
            subjonctif: {
                je: "rappelle",
                tu: "rappelles",
                il: "rappelle",
                nous: "rappelions",
                vous: "rappeliez",
                ils: "rappellent",
            },
        }
    },
    mener: {
        info: {
            participe_passe: "mené",
            hilfsverb: "avoir",
            deutsch: "bringen",
        },
        forms: {
            present: {
                je: "mène",
                tu: "mènes",
                il: "mène",
                nous: "menons",
                vous: "menez",
                ils: "mènent",
            },
            imparfait: {
                je: "menais",
                tu: "menais",
                il: "menait",
                nous: "menions",
                vous: "meniez",
                ils: "menaient",
            },
            conditionnel: {
                je: "mènerais",
                tu: "mènerais",
                il: "mènerait",
                nous: "mènerions",
                vous: "mèneriez",
                ils: "mèneraient",
            },
            futur_simple: {
                je: "mènerai",
                tu: "mèneras",
                il: "mènera",
                nous: "mènerons",
                vous: "mènerez",
                ils: "mèneront",
            },
            imperatif: {
                tu: "mène",
                nous: "menons",
                vous: "menez",
            },
            subjonctif: {
                je: "mène",
                tu: "mènes",
                il: "mène",
                nous: "menions",
                vous: "meniez",
                ils: "mènent",
            },
        }
    },
    peser: {
        info: {
            participe_passe: "pesé",
            hilfsverb: "avoir",
            deutsch: "wiegen",
        },
        forms: {
            present: {
                je: "pèse",
                tu: "pèses",
                il: "pèse",
                nous: "pesons",
                vous: "pesez",
                ils: "pèsent",
            },
            imparfait: {
                je: "pesais",
                tu: "pesais",
                il: "pesait",
                nous: "pesions",
                vous: "pesiez",
                ils: "pesaient",
            },
            conditionnel: {
                je: "pèserais",
                tu: "pèserais",
                il: "pèserait",
                nous: "pèserions",
                vous: "pèseriez",
                ils: "pèseraient",
            },
            futur_simple: {
                je: "pèserai",
                tu: "pèseras",
                il: "pèsera",
                nous: "pèserons",
                vous: "pèserez",
                ils: "pèseront",
            },
            imperatif: {
                tu: "pèse",
                nous: "pesons",
                vous: "pesez",
            },
            subjonctif: {
                je: "pèse",
                tu: "pèses",
                il: "pèse",
                nous: "pesions",
                vous: "pesiez",
                ils: "pèsent",
            },
        }
    },
    lever: {
        info: {
            participe_passe: "levé",
            hilfsverb: "avoir",
            deutsch: "aufheben",
        },
        forms: {
            present: {
                je: "lève",
                tu: "lèves",
                il: "lève",
                nous: "levons",
                vous: "levez",
                ils: "lèvent",
            },
            imparfait: {
                je: "levais",
                tu: "levais",
                il: "levait",
                nous: "levions",
                vous: "leviez",
                ils: "levaient",
            },
            conditionnel: {
                je: "lèverais",
                tu: "lèverais",
                il: "lèverait",
                nous: "lèverions",
                vous: "lèveriez",
                ils: "lèveraient",
            },
            futur_simple: {
                je: "lèverai",
                tu: "lèveras",
                il: "lèvera",
                nous: "lèverons",
                vous: "lèverez",
                ils: "lèveront",
            },
            imperatif: {
                tu: "lève",
                nous: "levons",
                vous: "levez",
            },
            subjonctif: {
                je: "lève",
                tu: "lèves",
                il: "lève",
                nous: "levions",
                vous: "leviez",
                ils: "lèvent",
            },
        }
    },
    se_lever: {
        info: {
            participe_passe: "levé",
            hilfsverb: "être",
            deutsch: "aufstehen",
        },
        forms: {
            present: {
                je: "me lève",
                tu: "te lève",
                il: "se lève",
                nous: "nous levons",
                vous: "vous levez",
                ils: "se lèvent",
            },
            imparfait: {
                je: "me levais",
                tu: "te levais",
                il: "se levait",
                nous: "nous levions",
                vous: "vous leviez",
                ils: "se levaient",
            },
            conditionnel: {
                je: "lèverais",
                tu: "lèverais",
                il: "lèverait",
                nous: "lèverions",
                vous: "lèveriez",
                ils: "lèveraient",
            },
            futur_simple: {
                je: "lèverai",
                tu: "lèveras",
                il: "lèvera",
                nous: "lèverons",
                vous: "lèverez",
                ils: "lèveront",
            },
            imperatif: {
                tu: "lève-toi",
                nous: "levons-nous",
                vous: "levez-vous",
            },
            subjonctif: {
                je: "me lève",
                tu: "te lèves",
                il: "se lève",
                nous: "nous levions",
                vous: "vous leviez",
                ils: "se lèvent",
            },
        }
    },
    enlever: {
        info: {
            participe_passe: "enlevé",
            hilfsverb: "avoir",
            deutsch: "entfernen",
        },
        forms: {
            present: {
                je: "enlève",
                tu: "enlèves",
                il: "enlève",
                nous: "enlevons",
                vous: "enlevez",
                ils: "enlèvent",
            },
            imparfait: {
                je: "enlevais",
                tu: "enlevais",
                il: "enlevait",
                nous: "enlevions",
                vous: "enleviez",
                ils: "enlevaient",
            },
            conditionnel: {
                je: "enlèverais",
                tu: "enlèverais",
                il: "enlèverait",
                nous: "enlèverions",
                vous: "enlèveriez",
                ils: "enlèveraient",
            },
            futur_simple: {
                je: "enlèverai",
                tu: "enlèveras",
                il: "enlèvera",
                nous: "enlèverons",
                vous: "enlèverez",
                ils: "enlèveront",
            },
            imperatif: {
                tu: "enlève",
                nous: "enlevons",
                vous: "enlevez",
            },
            subjonctif: {
                je: "enlève",
                tu: "enlèves",
                il: "enlève",
                nous: "enlevions",
                vous: "enleviez",
                ils: "enlèvent",
            },
        }
    },
    espérer: {
        info: {
            participe_passe: "espéré",
            hilfsverb: "avoir",
            deutsch: "hoffen",
        },
        forms: {
            present: {
                je: "espère",
                tu: "espères",
                il: "espère",
                nous: "espérons",
                vous: "espérez",
                ils: "espèrent",
            },
            imparfait: {
                je: "espérais",
                tu: "espérais",
                il: "espérait",
                nous: "espérions",
                vous: "espériez",
                ils: "espéraient",
            },
            conditionnel: {
                je: "espérerais",
                tu: "espérerais",
                il: "espérerait",
                nous: "espérerions",
                vous: "espéreriez",
                ils: "espéreraient",
            },
            futur_simple: {
                je: "espérerai",
                tu: "espéreras",
                il: "espérera",
                nous: "espérerons",
                vous: "espérerez",
                ils: "espéreront",
            },
            imperatif: {
                tu: "espère",
                nous: "espérons",
                vous: "espérez",
            },
            subjonctif: {
                je: "espère",
                tu: "espères",
                il: "espère",
                nous: "espérions",
                vous: "espériez",
                ils: "espérent",
            },
        }
    },
    compléter: {
        info: {
            participe_passe: "complété",
            hilfsverb: "avoir",
            deutsch: "ergänzen",
        },
        forms: {
            present: {
                je: "complète",
                tu: "complètes",
                il: "complète",
                nous: "complétons",
                vous: "complétez",
                ils: "complètent",
            },
            imparfait: {
                je: "complétais",
                tu: "complétais",
                il: "complétait",
                nous: "complétions",
                vous: "complétiez",
                ils: "complétaient",
            },
            conditionnel: {
                je: "compléterais",
                tu: "compléterais",
                il: "compléterait",
                nous: "compléterions",
                vous: "compléteriez",
                ils: "compléteraient",
            },
            futur_simple: {
                je: "compléterai",
                tu: "compléteras",
                il: "complétera",
                nous: "compléterons",
                vous: "compléterez",
                ils: "compléteront",
            },
            imperatif: {
                tu: "complète",
                nous: "complétons",
                vous: "complétez",
            },
            subjonctif: {
                je: "complète",
                tu: "complètes",
                il: "complète",
                nous: "complétions",
                vous: "complétiez",
                ils: "complètent",
            },
        }
    },
    se_promener: {
        info: {
            participe_passe: "promené",
            hilfsverb: "être",
            deutsch: "spazieren",
        },
        forms: {
            present: {
                je: "me promène",
                tu: "te promènes",
                il: "se promène",
                nous: "nous promenons",
                vous: "vous promenez",
                ils: "se promènent",
            },
            imparfait: {
                je: "me promenais",
                tu: "te promenais",
                il: "se promenait",
                nous: "nous promenions",
                vous: "vous promeniez",
                ils: "se promenaient",
            },
            conditionnel: {
                je: "me promènerais",
                tu: "te promènerais",
                il: "se promènerait",
                nous: "nous promènerions",
                vous: "vous promèneriez",
                ils: "se promèneraient",
            },
            futur_simple: {
                je: "me promènerai",
                tu: "te promèneras",
                il: "se promènera",
                nous: "nous promènerons",
                vous: "vous promènerez",
                ils: "se promèneront",
            },
            imperatif: {
                tu: "promène-toi",
                nous: "promenons-nous",
                vous: "promenez-vous",
            },
            subjonctif: {
                je: "me promène",
                tu: "te promènes",
                il: "se promène",
                nous: "nous promenions",
                vous: "vous promeniez",
                ils: "se promènent",
            },
        }
    },
    protéger: {
        info: {
            participe_passe: "protégé",
            hilfsverb: "avoir",
            deutsch: "schützen",
        },
        forms: {
            present: {
                je: "protège",
                tu: "protèges",
                il: "protège",
                nous: "protégons",
                vous: "protégez",
                ils: "protègent",
            },
            imparfait: {
                je: "protégeais",
                tu: "protégeais",
                il: "protégeait",
                nous: "protégions",
                vous: "protégiez",
                ils: "protégeaient",
            },
            conditionnel: {
                je: "protégerais",
                tu: "protégerais",
                il: "protégerait",
                nous: "protégerions",
                vous: "protégeriez",
                ils: "protégeraient",
            },
            futur_simple: {
                je: "protégerai",
                tu: "protégeras",
                il: "protégera",
                nous: "protégerons",
                vous: "protégerez",
                ils: "protégeront",
            },
            imperatif: {
                tu: "protège",
                nous: "protégeons",
                vous: "protégez",
            },
            subjonctif: {
                je: "protège",
                tu: "protèges",
                il: "protège",
                nous: "protégions",
                vous: "protégiez",
                ils: "protègent",
            },
        }
    },
    inquiéter: {
        info: {
            participe_passe: "inquiété",
            hilfsverb: "avoir",
            deutsch: "beunruhigen",
        },
        forms: {
            present: {
                je: "inquiète",
                tu: "inquiètes",
                il: "inquiète",
                nous: "inquiétons",
                vous: "inquiétez",
                ils: "inquiètent",
            },
            imparfait: {
                je: "inquiétais",
                tu: "inquiétais",
                il: "inquiétait",
                nous: "inquiétions",
                vous: "inquiétiez",
                ils: "inquiétaient",
            },
            conditionnel: {
                je: "inquiéterais",
                tu: "inquiéterais",
                il: "inquiéterait",
                nous: "inquiéterions",
                vous: "inquiéteriez",
                ils: "inquiéteraient",
            },
            futur_simple: {
                je: "inquiéterai",
                tu: "inquiéteras",
                il: "inquiétera",
                nous: "inquiéterons",
                vous: "inquiéterez",
                ils: "inquiéteront",
            },
            imperatif: {
                tu: "inquiète",
                nous: "inquiétons",
                vous: "inquiétez",
            },
            subjonctif: {
                je: "inquiète",
                tu: "inquiètes",
                il: "inquiète",
                nous: "inquiétions",
                vous: "inquiétiez",
                ils: "inquiètent",
            },
        }
    },    
    se_inquiéter: {
        info: {
            participe_passe: "inquiété",
            hilfsverb: "avoir",
            deutsch: "beunruhigen",
        },
        forms: {
            present: {
                je: "m'inquiète",
                tu: "t'inquiètes",
                il: "s'inquiète",
                nous: "nous inquiétons",
                vous: "vous inquiétez",
                ils: "s'inquiètent",
            },
            imparfait: {
                je: "m'inquiétais",
                tu: "t'inquiétais",
                il: "s'inquiétait",
                nous: "nous inquiétions",
                vous: "vous inquiétiez",
                ils: "s'inquiétaient",
            },
            conditionnel: {
                je: "m'inquiéterais",
                tu: "t'inquiéterais",
                il: "s'inquiéterait",
                nous: "nous inquiéterions",
                vous: "vous inquiéteriez",
                ils: "s'inquiéteraient",
            },
            futur_simple: {
                je: "m'inquiéterai",
                tu: "t'inquiéteras",
                il: "s'inquiétera",
                nous: "nous inquiéterons",
                vous: "vous inquiéterez",
                ils: "s'inquiéteront",
            },
            imperatif: {
                tu: "inquiète-toi",
                nous: "inquiétons-nous",
                vous: "inquiétez-vous",
            },
            subjonctif: {
                je: "m'inquiète",
                tu: "t'inquiètes",
                il: "s'inquiète",
                nous: "nous inquiétions",
                vous: "vous inquiétiez",
                ils: "s'inquiètent",
            },
        }
    }
};